import { IStudent } from "@/types/Student";

export const students: IStudent[] = [
  {
    cedula: "100000001",
    nombre: "Carlos",
    apellido: "Pérez",
    estado: "ESPERA",
    ficha: "10-A",
    correo: "carlos.perez@example.com",
  },
  {
    cedula: "100000002",
    nombre: "María",
    apellido: "Gómez",
    estado: "LLEGO",
    ficha: "10-A",
    correo: "maria.gomez@example.com",
  },
  {
    cedula: "100000003",
    nombre: "Juan",
    apellido: "Rodríguez",
    estado: "NO_VINO",
    ficha: "10-B",
    correo: "juan.rodriguez@example.com",
  },
  {
    cedula: "100000004",
    nombre: "Laura",
    apellido: "Sánchez",
    estado: "ESPERA",
    ficha: "10-B",
    correo: "laura.sanchez@example.com",
  },
  {
    cedula: "100000005",
    nombre: "Andrés",
    apellido: "Ramírez",
    estado: "LLEGO",
    ficha: "10-C",
    correo: "andres.ramirez@example.com",
  },
  {
    cedula: "100000006",
    nombre: "Sofía",
    apellido: "Morales",
    estado: "NO_VINO",
    ficha: "10-C",
    correo: "sofia.morales@example.com",
  },
  {
    cedula: "100000007",
    nombre: "Pedro",
    apellido: "Castillo",
    estado: "ESPERA",
    ficha: "10-D",
    correo: "pedro.castillo@example.com",
  },
  {
    cedula: "100000008",
    nombre: "Ana",
    apellido: "Torres",
    estado: "LLEGO",
    ficha: "10-D",
    correo: "ana.torres@example.com",
  },
  {
    cedula: "100000009",
    nombre: "Ricardo",
    apellido: "Vargas",
    estado: "NO_VINO",
    ficha: "10-E",
    correo: "ricardo.vargas@example.com",
  },
  {
    cedula: "100000010",
    nombre: "Valentina",
    apellido: "Cruz",
    estado: "ESPERA",
    ficha: "10-E",
    correo: "valentina.cruz@example.com",
  },
  {
    cedula: "100000011",
    nombre: "Jorge",
    apellido: "Herrera",
    estado: "LLEGO",
    ficha: "10-F",
    correo: "jorge.herrera@example.com",
  },
  {
    cedula: "100000012",
    nombre: "Camila",
    apellido: "Díaz",
    estado: "NO_VINO",
    ficha: "10-F",
    correo: "camila.diaz@example.com",
  },
  {
    cedula: "100000013",
    nombre: "Luis",
    apellido: "Romero",
    estado: "ESPERA",
    ficha: "10-G",
    correo: "luis.romero@example.com",
  },
  {
    cedula: "100000014",
    nombre: "Elena",
    apellido: "Navarro",
    estado: "LLEGO",
    ficha: "10-G",
    correo: "elena.navarro@example.com",
  },
  {
    cedula: "100000015",
    nombre: "Manuel",
    apellido: "Pardo",
    estado: "NO_VINO",
    ficha: "10-H",
    correo: "manuel.pardo@example.com",
  },
  {
    cedula: "100000016",
    nombre: "Isabella",
    apellido: "Ríos",
    estado: "ESPERA",
    ficha: "10-H",
    correo: "isabella.rios@example.com",
  },
  {
    cedula: "100000017",
    nombre: "Diego",
    apellido: "Soto",
    estado: "LLEGO",
    ficha: "10-I",
    correo: "diego.soto@example.com",
  },
  {
    cedula: "100000018",
    nombre: "Gabriela",
    apellido: "León",
    estado: "NO_VINO",
    ficha: "10-I",
    correo: "gabriela.leon@example.com",
  },
  {
    cedula: "100000019",
    nombre: "Fernando",
    apellido: "Aguilar",
    estado: "ESPERA",
    ficha: "10-J",
    correo: "fernando.aguilar@example.com",
  },
  {
    cedula: "100000020",
    nombre: "Daniela",
    apellido: "Mendoza",
    estado: "LLEGO",
    ficha: "10-J",
    correo: "daniela.mendoza@example.com",
  },
  // 🔽 Agrega más hasta llegar a 50 🔽
  {
    cedula: "100000021",
    nombre: "Alejandro",
    apellido: "Cárdenas",
    estado: "NO_VINO",
    ficha: "10-K",
    correo: "alejandro.cardenas@example.com",
  },
  {
    cedula: "100000022",
    nombre: "Paula",
    apellido: "Salazar",
    estado: "ESPERA",
    ficha: "10-K",
    correo: "paula.salazar@example.com",
  },
  {
    cedula: "100000023",
    nombre: "Sebastián",
    apellido: "Muñoz",
    estado: "LLEGO",
    ficha: "10-L",
    correo: "sebastian.munoz@example.com",
  },
  {
    cedula: "100000024",
    nombre: "Natalia",
    apellido: "Pineda",
    estado: "NO_VINO",
    ficha: "10-L",
    correo: "natalia.pineda@example.com",
  },
  {
    cedula: "100000025",
    nombre: "Cristian",
    apellido: "Ochoa",
    estado: "ESPERA",
    ficha: "10-M",
    correo: "cristian.ochoa@example.com",
  },
  {
    cedula: "100000026",
    nombre: "Mónica",
    apellido: "Rangel",
    estado: "LLEGO",
    ficha: "10-M",
    correo: "monica.rangel@example.com",
  },
  {
    cedula: "100000027",
    nombre: "Felipe",
    apellido: "Arias",
    estado: "NO_VINO",
    ficha: "10-N",
    correo: "felipe.arias@example.com",
  },
  {
    cedula: "100000028",
    nombre: "Carolina",
    apellido: "Duarte",
    estado: "ESPERA",
    ficha: "10-N",
    correo: "carolina.duarte@example.com",
  },
  {
    cedula: "100000029",
    nombre: "Tomás",
    apellido: "Rueda",
    estado: "LLEGO",
    ficha: "10-O",
    correo: "tomas.rueda@example.com",
  },
  {
    cedula: "100000030",
    nombre: "Juliana",
    apellido: "Páez",
    estado: "NO_VINO",
    ficha: "10-O",
    correo: "juliana.paez@example.com",
  },
  {
    cedula: "100000031",
    nombre: "Héctor",
    apellido: "Silva",
    estado: "ESPERA",
    ficha: "10-P",
    correo: "hector.silva@example.com",
  },
  {
    cedula: "100000032",
    nombre: "Angela",
    apellido: "Correa",
    estado: "LLEGO",
    ficha: "10-P",
    correo: "angela.correa@example.com",
  },
  {
    cedula: "100000033",
    nombre: "Mauricio",
    apellido: "Peña",
    estado: "NO_VINO",
    ficha: "10-Q",
    correo: "mauricio.pena@example.com",
  },
  {
    cedula: "100000034",
    nombre: "Sara",
    apellido: "Molina",
    estado: "ESPERA",
    ficha: "10-Q",
    correo: "sara.molina@example.com",
  },
  {
    cedula: "100000035",
    nombre: "Esteban",
    apellido: "Lozano",
    estado: "LLEGO",
    ficha: "10-R",
    correo: "esteban.lozano@example.com",
  },
  {
    cedula: "100000036",
    nombre: "Verónica",
    apellido: "Castro",
    estado: "NO_VINO",
    ficha: "10-R",
    correo: "veronica.castro@example.com",
  },
  {
    cedula: "100000037",
    nombre: "Óscar",
    apellido: "Beltrán",
    estado: "ESPERA",
    ficha: "10-S",
    correo: "oscar.beltran@example.com",
  },
  {
    cedula: "100000038",
    nombre: "Adriana",
    apellido: "Cifuentes",
    estado: "LLEGO",
    ficha: "10-S",
    correo: "adriana.cifuentes@example.com",
  },
  {
    cedula: "100000039",
    nombre: "Rafael",
    apellido: "Ortega",
    estado: "NO_VINO",
    ficha: "10-T",
    correo: "rafael.ortega@example.com",
  },
  {
    cedula: "100000040",
    nombre: "Liliana",
    apellido: "Marín",
    estado: "ESPERA",
    ficha: "10-T",
    correo: "liliana.marin@example.com",
  },
  {
    cedula: "100000041",
    nombre: "David",
    apellido: "Parra",
    estado: "LLEGO",
    ficha: "10-U",
    correo: "david.parra@example.com",
  },
  {
    cedula: "100000042",
    nombre: "Patricia",
    apellido: "Serrano",
    estado: "NO_VINO",
    ficha: "10-U",
    correo: "patricia.serrano@example.com",
  },
  {
    cedula: "100000043",
    nombre: "Rodrigo",
    apellido: "Villalba",
    estado: "ESPERA",
    ficha: "10-V",
    correo: "rodrigo.villalba@example.com",
  },
  {
    cedula: "100000044",
    nombre: "Lucía",
    apellido: "Quintero",
    estado: "LLEGO",
    ficha: "10-V",
    correo: "lucia.quintero@example.com",
  },
  {
    cedula: "100000045",
    nombre: "Martín",
    apellido: "Acosta",
    estado: "NO_VINO",
    ficha: "10-W",
    correo: "martin.acosta@example.com",
  },
  {
    cedula: "100000046",
    nombre: "Claudia",
    apellido: "Ramírez",
    estado: "ESPERA",
    ficha: "10-W",
    correo: "claudia.ramirez@example.com",
  },
  {
    cedula: "100000047",
    nombre: "Álvaro",
    apellido: "Espinosa",
    estado: "LLEGO",
    ficha: "10-X",
    correo: "alvaro.espinosa@example.com",
  },
  {
    cedula: "100000048",
    nombre: "Marisol",
    apellido: "Benítez",
    estado: "NO_VINO",
    ficha: "10-X",
    correo: "marisol.benitez@example.com",
  },
  {
    cedula: "100000049",
    nombre: "Hernán",
    apellido: "Duarte",
    estado: "ESPERA",
    ficha: "10-Y",
    correo: "hernan.duarte@example.com",
  },
  {
    cedula: "100000050",
    nombre: "Catalina",
    apellido: "Suárez",
    estado: "LLEGO",
    ficha: "10-Y",
    correo: "catalina.suarez@example.com",
  },
];

export default students;
