import { IUser } from "@/types/User";

export const data: IUser[] = [
  {
    id: 1,
    name: "Carlos Pérez",
    email: "carlos.perez@example.com",
    rol: "admin",
  },
  {
    id: 2,
    name: "María Gómez",
    email: "maria.gomez@example.com",
    rol: "profesor",
  },
  {
    id: 3,
    name: "Juan Rodríguez",
    email: "juan.rodriguez@example.com",
    rol: "alumno",
  },
  {
    id: 4,
    name: "Laura Sánchez",
    email: "laura.sanchez@example.com",
    rol: "alumno",
  },
  {
    id: 5,
    name: "Andrés Ramírez",
    email: "andres.ramirez@example.com",
    rol: "profesor",
  },
  {
    id: 6,
    name: "Sofía Morales",
    email: "sofia.morales@example.com",
    rol: "alumno",
  },
  {
    id: 7,
    name: "Pedro Castillo",
    email: "pedro.castillo@example.com",
    rol: "profesor",
  },
  { id: 8, name: "Ana Torres", email: "ana.torres@example.com", rol: "alumno" },
  {
    id: 9,
    name: "Ricardo Vargas",
    email: "ricardo.vargas@example.com",
    rol: "admin",
  },
  {
    id: 10,
    name: "Valentina Cruz",
    email: "valentina.cruz@example.com",
    rol: "profesor",
  },
  {
    id: 11,
    name: "Jorge Herrera",
    email: "jorge.herrera@example.com",
    rol: "alumno",
  },
  {
    id: 12,
    name: "Camila Díaz",
    email: "camila.diaz@example.com",
    rol: "alumno",
  },
  {
    id: 13,
    name: "Luis Romero",
    email: "luis.romero@example.com",
    rol: "profesor",
  },
  {
    id: 14,
    name: "Elena Navarro",
    email: "elena.navarro@example.com",
    rol: "profesor",
  },
  {
    id: 15,
    name: "Manuel Pardo",
    email: "manuel.pardo@example.com",
    rol: "alumno",
  },
  {
    id: 16,
    name: "Isabella Ríos",
    email: "isabella.rios@example.com",
    rol: "alumno",
  },
  {
    id: 17,
    name: "Diego Soto",
    email: "diego.soto@example.com",
    rol: "profesor",
  },
  {
    id: 18,
    name: "Gabriela León",
    email: "gabriela.leon@example.com",
    rol: "alumno",
  },
  {
    id: 19,
    name: "Fernando Aguilar",
    email: "fernando.aguilar@example.com",
    rol: "admin",
  },
  {
    id: 20,
    name: "Daniela Mendoza",
    email: "daniela.mendoza@example.com",
    rol: "profesor",
  },
  {
    id: 21,
    name: "Alejandro Cárdenas",
    email: "alejandro.cardenas@example.com",
    rol: "alumno",
  },
  {
    id: 22,
    name: "Paula Salazar",
    email: "paula.salazar@example.com",
    rol: "alumno",
  },
  {
    id: 23,
    name: "Sebastián Muñoz",
    email: "sebastian.munoz@example.com",
    rol: "profesor",
  },
  {
    id: 24,
    name: "Natalia Pineda",
    email: "natalia.pineda@example.com",
    rol: "profesor",
  },
  {
    id: 25,
    name: "Cristian Ochoa",
    email: "cristian.ochoa@example.com",
    rol: "alumno",
  },
  {
    id: 26,
    name: "Mónica Rangel",
    email: "monica.rangel@example.com",
    rol: "alumno",
  },
  {
    id: 27,
    name: "Felipe Arias",
    email: "felipe.arias@example.com",
    rol: "profesor",
  },
  {
    id: 28,
    name: "Carolina Duarte",
    email: "carolina.duarte@example.com",
    rol: "alumno",
  },
  {
    id: 29,
    name: "Tomás Rueda",
    email: "tomas.rueda@example.com",
    rol: "profesor",
  },
  {
    id: 30,
    name: "Juliana Páez",
    email: "juliana.paez@example.com",
    rol: "alumno",
  },
  {
    id: 31,
    name: "Héctor Silva",
    email: "hector.silva@example.com",
    rol: "admin",
  },
  {
    id: 32,
    name: "Angela Correa",
    email: "angela.correa@example.com",
    rol: "profesor",
  },
  {
    id: 33,
    name: "Mauricio Peña",
    email: "mauricio.pena@example.com",
    rol: "alumno",
  },
  {
    id: 34,
    name: "Sara Molina",
    email: "sara.molina@example.com",
    rol: "alumno",
  },
  {
    id: 35,
    name: "Esteban Lozano",
    email: "esteban.lozano@example.com",
    rol: "profesor",
  },
  {
    id: 36,
    name: "Verónica Castro",
    email: "veronica.castro@example.com",
    rol: "alumno",
  },
  {
    id: 37,
    name: "Óscar Beltrán",
    email: "oscar.beltran@example.com",
    rol: "profesor",
  },
  {
    id: 38,
    name: "Adriana Cifuentes",
    email: "adriana.cifuentes@example.com",
    rol: "alumno",
  },
  {
    id: 39,
    name: "Rafael Ortega",
    email: "rafael.ortega@example.com",
    rol: "profesor",
  },
  {
    id: 40,
    name: "Liliana Marín",
    email: "liliana.marin@example.com",
    rol: "alumno",
  },
  {
    id: 41,
    name: "David Parra",
    email: "david.parra@example.com",
    rol: "alumno",
  },
  {
    id: 42,
    name: "Patricia Serrano",
    email: "patricia.serrano@example.com",
    rol: "profesor",
  },
  {
    id: 43,
    name: "Rodrigo Villalba",
    email: "rodrigo.villalba@example.com",
    rol: "admin",
  },
  {
    id: 44,
    name: "Lucía Quintero",
    email: "lucia.quintero@example.com",
    rol: "profesor",
  },
  {
    id: 45,
    name: "Martín Acosta",
    email: "martin.acosta@example.com",
    rol: "alumno",
  },
  {
    id: 46,
    name: "Claudia Ramírez",
    email: "claudia.ramirez@example.com",
    rol: "alumno",
  },
  {
    id: 47,
    name: "Álvaro Espinosa",
    email: "alvaro.espinosa@example.com",
    rol: "profesor",
  },
  {
    id: 48,
    name: "Marisol Benítez",
    email: "marisol.benitez@example.com",
    rol: "alumno",
  },
  {
    id: 49,
    name: "Hernán Duarte",
    email: "hernan.duarte@example.com",
    rol: "profesor",
  },
  {
    id: 50,
    name: "Catalina Suárez",
    email: "catalina.suarez@example.com",
    rol: "alumno",
  },
];

export default data;
